"""fix all foreign key cascade rules

Revision ID: 00a92496fe45
Revises: 18b57c604011
Create Date: 2026-05-03 00:49:28.892623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a92496fe45'
down_revision: Union[str, Sequence[str], None] = '18b57c604011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bookings_room_id'), 'bookings', ['room_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.drop_constraint(op.f('bookings_room_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_user_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('hostels', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('hostels_owner_id_fkey'), 'hostels', type_='foreignkey')
    op.create_foreign_key(None, 'hostels', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_refund_approved_by'), 'payments', ['refund_approved_by'], unique=False)
    op.create_index(op.f('ix_payments_refund_requested_by'), 'payments', ['refund_requested_by'], unique=False)
    op.drop_constraint(op.f('payments_refund_approved_by_fkey'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('payments_booking_id_fkey'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('payments_refund_requested_by_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'users', ['refund_requested_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'payments', 'users', ['refund_approved_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'payments', 'bookings', ['booking_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_reservations_room_id'), 'reservations', ['room_id'], unique=False)
    op.create_index(op.f('ix_reservations_user_id'), 'reservations', ['user_id'], unique=False)
    op.drop_constraint(op.f('reservations_room_id_fkey'), 'reservations', type_='foreignkey')
    op.drop_constraint(op.f('reservations_user_id_fkey'), 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reservations', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_room_type_images_room_type_id'), 'room_type_images', ['room_type_id'], unique=False)
    op.drop_constraint(op.f('room_type_images_room_type_id_fkey'), 'room_type_images', type_='foreignkey')
    op.create_foreign_key(None, 'room_type_images', 'room_types', ['room_type_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_room_types_hostel_id'), 'room_types', ['hostel_id'], unique=False)
    op.drop_constraint(op.f('room_types_hostel_id_fkey'), 'room_types', type_='foreignkey')
    op.create_foreign_key(None, 'room_types', 'hostels', ['hostel_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_rooms_hostel_id'), 'rooms', ['hostel_id'], unique=False)
    op.create_index(op.f('ix_rooms_room_type_id'), 'rooms', ['room_type_id'], unique=False)
    op.drop_constraint(op.f('rooms_room_type_id_fkey'), 'rooms', type_='foreignkey')
    op.drop_constraint(op.f('rooms_hostel_id_fkey'), 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'room_types', ['room_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'rooms', 'hostels', ['hostel_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('rooms_hostel_id_fkey'), 'rooms', 'hostels', ['hostel_id'], ['id'])
    op.create_foreign_key(op.f('rooms_room_type_id_fkey'), 'rooms', 'room_types', ['room_type_id'], ['id'])
    op.drop_index(op.f('ix_rooms_room_type_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_hostel_id'), table_name='rooms')
    op.drop_constraint(None, 'room_types', type_='foreignkey')
    op.create_foreign_key(op.f('room_types_hostel_id_fkey'), 'room_types', 'hostels', ['hostel_id'], ['id'])
    op.drop_index(op.f('ix_room_types_hostel_id'), table_name='room_types')
    op.drop_constraint(None, 'room_type_images', type_='foreignkey')
    op.create_foreign_key(op.f('room_type_images_room_type_id_fkey'), 'room_type_images', 'room_types', ['room_type_id'], ['id'])
    op.drop_index(op.f('ix_room_type_images_room_type_id'), table_name='room_type_images')
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key(op.f('reservations_user_id_fkey'), 'reservations', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('reservations_room_id_fkey'), 'reservations', 'rooms', ['room_id'], ['id'])
    op.drop_index(op.f('ix_reservations_user_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_room_id'), table_name='reservations')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_refund_requested_by_fkey'), 'payments', 'users', ['refund_requested_by'], ['id'])
    op.create_foreign_key(op.f('payments_booking_id_fkey'), 'payments', 'bookings', ['booking_id'], ['id'])
    op.create_foreign_key(op.f('payments_refund_approved_by_fkey'), 'payments', 'users', ['refund_approved_by'], ['id'])
    op.drop_index(op.f('ix_payments_refund_requested_by'), table_name='payments')
    op.drop_index(op.f('ix_payments_refund_approved_by'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_constraint(None, 'hostels', type_='foreignkey')
    op.create_foreign_key(op.f('hostels_owner_id_fkey'), 'hostels', 'users', ['owner_id'], ['id'])
    op.alter_column('hostels', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_user_id_fkey'), 'bookings', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('bookings_room_id_fkey'), 'bookings', 'rooms', ['room_id'], ['id'])
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_room_id'), table_name='bookings')
    # ### end Alembic commands ###
