"""add cascade delete to user foreign keys

Revision ID: 18b57c604011
Revises: 0846e7ce04e6
Create Date: 2026-05-03 00:18:38.032563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18b57c604011'
down_revision: Union[str, Sequence[str], None] = '0846e7ce04e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('landlord_requests_user_id_fkey'), 'landlord_requests', type_='foreignkey')
    op.drop_constraint(op.f('landlord_requests_admin_id_fkey'), 'landlord_requests', type_='foreignkey')
    op.create_foreign_key(None, 'landlord_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'landlord_requests', 'users', ['admin_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'landlord_requests', type_='foreignkey')
    op.drop_constraint(None, 'landlord_requests', type_='foreignkey')
    op.create_foreign_key(op.f('landlord_requests_admin_id_fkey'), 'landlord_requests', 'users', ['admin_id'], ['id'])
    op.create_foreign_key(op.f('landlord_requests_user_id_fkey'), 'landlord_requests', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
