"""Removed the password otp column

Revision ID: 2bf8181307bd
Revises: 319565a329fa
Create Date: 2026-03-30 16:39:22.956735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf8181307bd'
down_revision: Union[str, Sequence[str], None] = '319565a329fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_otp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_otp', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
