"""Remove otp column from user table

Revision ID: 319565a329fa
Revises: 8e47e9a92b59
Create Date: 2026-03-30 16:35:43.303701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '319565a329fa'
down_revision: Union[str, Sequence[str], None] = '8e47e9a92b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_expiry')
    op.drop_column('users', 'phone_otp')
    op.drop_column('users', 'email_otp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_otp', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone_otp', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('otp_expiry', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
