"""Added public_id column in RoomImage table

Revision ID: 47bc56effc14
Revises: ad2a18bc7f8f
Create Date: 2026-03-26 15:49:12.634937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47bc56effc14'
down_revision: Union[str, Sequence[str], None] = 'ad2a18bc7f8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_images', sa.Column('public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_images', 'public_id')
    # ### end Alembic commands ###
