"""Add Reservation model for pending bookings

Revision ID: 5a1bcaef2ad8
Revises: db64564865a1
Create Date: 2026-04-03 16:23:00.728434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a1bcaef2ad8'
down_revision: Union[str, Sequence[str], None] = 'db64564865a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('semester', sa.String(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('mpesa_checkout_request_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CONVERTED', name='reservationstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_mpesa_checkout_request_id'), 'reservations', ['mpesa_checkout_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_mpesa_checkout_request_id'), table_name='reservations')
    op.drop_table('reservations')
    # ### end Alembic commands ###
