"""Add Room and RoomImage tables; update User and Hostel

Revision ID: 5aae6a04b93f
Revises: f43419a4dc05
Create Date: 2026-03-23 22:33:24.883575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import String

# revision identifiers, used by Alembic.
revision: str = '5aae6a04b93f'
down_revision: Union[str, Sequence[str], None] = 'f43419a4dc05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('image_url', String(), nullable=False),
    sa.Column('image_type', String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hostel_id', sa.UUID(), nullable=False),
    sa.Column('room_number', String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('price_single', sa.Integer(), nullable=False),
    sa.Column('price_double', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('AVAILABLE', 'PARTIALLY_OCCUPIED', 'FULLY_OCCUPIED', 'MAINTENANCE', name='room_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostel_id', 'room_number', name='unique_room_per_hostel')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms')
    op.drop_table('room_images')
    # ### end Alembic commands ###
