"""update landlord_requests columns

Revision ID: 5e3bcc4227cc
Revises: 20c26d3c6da9
Create Date: 2026-03-07 15:00:41.689813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e3bcc4227cc'
down_revision: Union[str, Sequence[str], None] = '20c26d3c6da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   # 1. Create the ENUM type
    documenttype = postgresql.ENUM('TITLE_DEED', 'LEASE_AGREEMENT', 'AUTHORIZATION_LETTER', name='documenttype')
    documenttype.create(op.get_bind(), checkfirst=True)  # creates the ENUM if not exists

    # 2. Add the new columns
    op.add_column('landlord_requests', sa.Column('document_type', documenttype, nullable=False))
    op.add_column('landlord_requests', sa.Column('document_url', sa.String(), nullable=False))
    op.add_column('landlord_requests', sa.Column('document_public_id', sa.String(), nullable=False))
    op.add_column('landlord_requests', sa.Column('rejection_reason', sa.String(length=255), nullable=True))

    # 3. Add indexes if needed
    op.create_index('ix_landlord_requests_admin_id', 'landlord_requests', ['admin_id'])
    op.create_index('ix_landlord_requests_user_id', 'landlord_requests', ['user_id'])

    # 4. Drop old columns if needed
    op.drop_column('landlord_requests', 'reason')
    op.drop_column('landlord_requests', 'requested_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landlord_requests', 'document_type')
    op.drop_column('landlord_requests', 'document_url')
    op.drop_column('landlord_requests', 'document_public_id')
    op.drop_column('landlord_requests', 'rejection_reason')

    # Drop the ENUM type
    documenttype = postgresql.ENUM('TITLE_DEED', 'LEASE_AGREEMENT', 'AUTHORIZATION_LETTER', name='documenttype')
    documenttype.drop(op.get_bind(), checkfirst=True)

    # Optionally restore old columns
    op.add_column('landlord_requests', sa.Column('reason', sa.String(length=255), nullable=True))
    op.add_column('landlord_requests', sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
