"""add maintenance flag and occupancy constraint

Revision ID: 5ffe27c0c645
Revises: 5aae6a04b93f
Create Date: 2026-03-25 11:36:45.520662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ffe27c0c645'
down_revision: Union[str, Sequence[str], None] = '5aae6a04b93f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('current_occupancy', sa.Integer(), nullable=False))
    op.add_column('rooms', sa.Column('is_under_maintenance', sa.Boolean(), nullable=False))
    op.add_column('rooms', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'rooms', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'owner_id')
    op.drop_column('rooms', 'is_under_maintenance')
    op.drop_column('rooms', 'current_occupancy')
    # ### end Alembic commands ###
