"""Add pending_password and password_otp to User

Revision ID: 79297951ae0b
Revises: bcf2b5eee42a
Create Date: 2026-03-04 20:12:09.586815

"""
from sqlalchemy import String
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79297951ae0b'
down_revision: Union[str, Sequence[str], None] = 'bcf2b5eee42a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_password', String(length=128), nullable=True))
    op.add_column('users', sa.Column('password_otp', String(length=6), nullable=True))
    op.alter_column('users', 'otp_expiry',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'otp_expiry',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('users', 'password_otp')
    op.drop_column('users', 'pending_password')
    # ### end Alembic commands ###
