"""Create hostel, hostel_images, hostel_blocks, amenities, and hostel_amenities tables; add hostels relationship to User model

Revision ID: 7fde9f9c6b40
Revises: 92705997d8e7
Create Date: 2026-03-10 15:44:25.092089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fde9f9c6b40'
down_revision: Union[str, Sequence[str], None] = '92705997d8e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
