"""Add submitted_at to landlord_requests

Revision ID: 92705997d8e7
Revises: 5e3bcc4227cc
Create Date: 2026-03-08 14:54:28.532467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92705997d8e7'
down_revision: Union[str, Sequence[str], None] = '5e3bcc4227cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landlord_requests', sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landlord_requests', 'submitted_at')
    # ### end Alembic commands ###
