"""Add admin-reviewed relationship to LandlordRequest and User

Revision ID: 9cd74691080a
Revises: 0f0217e88a17
Create Date: 2026-02-25 11:59:19.758440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cd74691080a'
down_revision: Union[str, Sequence[str], None] = '0f0217e88a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
