"""add is_featured to hostels

Revision ID: a7835a810899
Revises: ec373e1cb121
Create Date: 2026-04-11 17:19:44.893048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7835a810899'
down_revision: Union[str, Sequence[str], None] = 'ec373e1cb121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostels', sa.Column('is_featured', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hostels', 'is_featured')
    # ### end Alembic commands ###
