"""Created the payment's domain model

Revision ID: a9d32ffc298c
Revises: 5ca1a1e3477b
Create Date: 2026-04-01 01:21:16.664125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9d32ffc298c'
down_revision: Union[str, Sequence[str], None] = '5ca1a1e3477b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('transaction_ref', sa.String(), nullable=True),
    sa.Column('checkout_request_id', sa.String(), nullable=True),
    sa.Column('refund_requested_by', sa.UUID(), nullable=True),
    sa.Column('refund_approved_by', sa.UUID(), nullable=True),
    sa.Column('refund_reason', sa.String(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['refund_approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['refund_requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    # ### end Alembic commands ###
