"""Fix RoomImage FK to Room

Revision ID: ad2a18bc7f8f
Revises: 5ffe27c0c645
Create Date: 2026-03-25 15:53:12.177440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2a18bc7f8f'
down_revision: Union[str, Sequence[str], None] = '5ffe27c0c645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'room_images', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room_images', type_='foreignkey')
    # ### end Alembic commands ###
