"""Create hostel, hostel_images, hostel_blocks, amenities, and hostel_amenities tables; add hostels relationship to User model

Revision ID: b3c235619589
Revises: 7fde9f9c6b40
Create Date: 2026-03-10 16:19:39.378745

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c235619589'
down_revision: Union[str, Sequence[str], None] = '7fde9f9c6b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amenities_name'), 'amenities', ['name'], unique=True)
    op.create_table('hostels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED', name='hostel_status'), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hostels_owner_id'), 'hostels', ['owner_id'], unique=False)
    op.create_table('hostel_amenities',
    sa.Column('hostel_id', sa.Uuid(), nullable=False),
    sa.Column('amenity_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.PrimaryKeyConstraint('hostel_id', 'amenity_id')
    )
    op.create_table('hostel_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hostel_id', sa.Uuid(), nullable=False),
    sa.Column('data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('previous_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hostel_blocks_hostel_id'), 'hostel_blocks', ['hostel_id'], unique=False)
    op.create_table('hostel_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hostel_id', sa.Uuid(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hostel_images_hostel_id'), 'hostel_images', ['hostel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hostel_images_hostel_id'), table_name='hostel_images')
    op.drop_table('hostel_images')
    op.drop_index(op.f('ix_hostel_blocks_hostel_id'), table_name='hostel_blocks')
    op.drop_table('hostel_blocks')
    op.drop_table('hostel_amenities')
    op.drop_index(op.f('ix_hostels_owner_id'), table_name='hostels')
    op.drop_table('hostels')
    op.drop_index(op.f('ix_amenities_name'), table_name='amenities')
    op.drop_table('amenities')
    # ### end Alembic commands ###
