"""Add pending fields and OTP fields to User

Revision ID: e0f734f7a2d4
Revises: 157b70188e21
Create Date: 2026-02-27 14:07:49.416752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e0f734f7a2d4'
down_revision: Union[str, Sequence[str], None] = '157b70188e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_email', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('pending_phone', sa.String(length=13), nullable=True))
    op.add_column('users', sa.Column('email_otp', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('phone_otp', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('otp_expiry', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_expiry')
    op.drop_column('users', 'phone_otp')
    op.drop_column('users', 'email_otp')
    op.drop_column('users', 'pending_phone')
    op.drop_column('users', 'pending_email')
    # ### end Alembic commands ###
