"""We made booking_id nullable at this point

Revision ID: ec373e1cb121
Revises: 5a1bcaef2ad8
Create Date: 2026-04-03 23:55:30.738191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec373e1cb121'
down_revision: Union[str, Sequence[str], None] = '5a1bcaef2ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'booking_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'booking_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
