"""Add is_deleted to Hostel

Revision ID: f43419a4dc05
Revises: 848960bf5bd2
Create Date: 2026-03-15 00:26:54.394023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f43419a4dc05'
down_revision: Union[str, Sequence[str], None] = '848960bf5bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostels', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hostels', 'is_deleted')
    # ### end Alembic commands ###
